apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: minecraft
    cyclops-ui.com/write-repo: https://github.com/KaradzaJuraj/templates-pub
    cyclops-ui.com/write-revision: main
  creationTimestamp: null
  name: huehue
spec:
  targetNamespace: default
  template:
    path: charts/minecraft
    repo: https://github.com/KaradzaJuraj/minecraft-server-charts
    sourceType: git
    version: cyclops
  values:
    affinity: {}
    deploymentAnnotations: {}
    deploymentLabels: {}
    envFrom: []
    extraDeploy: []
    extraEnv: {}
    extraPodSpec: {}
    extraVolumes: []
    image:
      pullPolicy: Always
      pullSecret: ""
      repository: itzg/minecraft-server
      tag: latest
    initContainers: []
    lifecycle:
      postStart: []
      preStop: []
    livenessProbe:
      command:
      - mc-health
      failureThreshold: 20
      initialDelaySeconds: 30
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    mcbackup:
      backupInterval: 24h
      backupMethod: tar
      compressMethod: gzip
      destDir: /backups
      enabled: false
      envFrom: []
      excludes: '*.jar,cache,logs'
      extraEnv: {}
      image:
        pullPolicy: IfNotPresent
        repository: itzg/mc-backup
        tag: latest
      initialDelay: 2m
      linkLatest: "false"
      pauseIfNoPlayers: "false"
      persistence:
        annotations: {}
        backupDir:
          Size: 1Gi
          accessModes:
          - ReadWriteOnce
          enabled: false
      pruneBackupsDays: 7
      pruneResticRetention: --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly
        75
      rcloneCompressMethod: gzip
      rconRetries: 5
      rconRetryInterval: 10s
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
      resticAdditionalTags: mc_backups
      resticEnvs: {}
      resticRepository: ""
      zstdParameters: -3 --long=25 --single-thread
    minecraftServer:
      allowNether: default
      announcePlayerAchievements: default
      autoCurseForge:
        apiKey:
          existingSecret: ""
          key: CHANGEME!
          secretKey: cf-api-key
        excludeMods: []
        fileId: ""
        filenameMatcher: ""
        forceSynchronize: false
        includeMods: []
        overridesSkipExisting: false
        pageUrl: ""
        parallelDownloads: 4
        setLevelFrom: ""
        slug: ""
      difficulty: easy
      enableCommandBlock: default
      enforceSecureProfile: default
      eula: true
      extraPorts: []
      extraServiceSpec: {}
      forceReDownload: false
      forcegameMode: default
      ftbLegacyJavaFixer: default
      gameMode: survival
      generateStructures: default
      hardcore: default
      jvmOpts: ""
      jvmXXOpts: ""
      levelType: DEFAULT
      maxBuildHeight: 256
      maxPlayers: 20
      maxTickTime: 60000
      maxWorldSize: 10000
      memory: 1024M
      modUrls: []
      modrinth:
        allowedVersionType: release
        optionalDependencies: false
        projects: []
      motd: Welcome to Minecraft on Kubernetes!
      onlineMode: default
      overrideServerProperties: false
      pluginUrls: []
      pvp: default
      query:
        enabled: false
        port: 25565
      rcon:
        enabled: false
        password: CHANGEME!
        port: 25575
        secretKey: rcon-password
        serviceType: ClusterIP
        withGeneratedPassword: false
      removeOldMods: false
      resourcePackEnforce: false
      serviceAnnotations: {}
      servicePort: 25565
      serviceType: ClusterIP
      spawnAnimals: default
      spawnMonsters: default
      spawnNPCs: default
      spawnProtection: 16
      spigetResources: []
      type: VANILLA
      vanillaTweaksShareCodes: []
      version: LATEST
      viewDistance: 10
      worldSaveName: world
    nodeSelector: {}
    persistence:
      annotations: {}
      dataDir:
        Size: 1Gi
        accessModes:
        - ReadWriteOnce
        enabled: false
      labels: {}
    podAnnotations: {}
    podLabels: {}
    podSecurityContext:
      fsGroup: 2000
      runAsGroup: 3000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    rconServiceAnnotations: {}
    rconServiceLabels: {}
    readinessProbe:
      command:
      - mc-health
      failureThreshold: 20
      initialDelaySeconds: 30
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    serviceAnnotations: {}
    serviceLabels: {}
    sidecarContainers: []
    startupProbe:
      command:
      - mc-health
      enabled: false
      failureThreshold: 30
      periodSeconds: 10
    strategyType: Recreate
    tolerations: []
    workloadAsStatefulSet: false
