apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: gitops-1
    cyclops-ui.com/write-repo: https://github.com/KaradzaJuraj/templates-pub
    cyclops-ui.com/write-revision: main
  creationTimestamp: null
  name: gitops-1
spec:
  targetNamespace: default
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    image: nginx
    name: demo-app
    replicas: 1
    service: true
    version: 1.14.2
