apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: jajavac
    cyclops-ui.com/write-repo: https://github.com/KaradzaJuraj/templates-pub
    cyclops-ui.com/write-revision: required-branch
  creationTimestamp: null
  name: jajavac
spec:
  targetNamespace: default
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    image: nginx
    name: demo-app
    replicas: 5
    service: false
    version: latest
status:
  iconURL: ""
  managedGVRs: null
  reconciliationStatus:
    errors: null
  templateResolvedVersion: ""
