{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.configmap.namespace }}
data:
  {{- range $key, $value := .Values.configmap.environment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}